name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: cargo build --target x86_64-unknown-linux-gnu --all --release && ls -lh target/release && mv target/release/gistr target/release/gistr_arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/gistr_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
